### PR TITLE
fix: incorrect font datepicker label

### LINKED ISSUE #128: [BUG] Incorrect font size of datepicker label
Based on our Figma design we set `body-2-comfortable` for datepicker label.

Current:
Screenshot 2023-04-03 at 09 00 00

Expected:
Screenshot 2023-04-03 at 09 00 06

### PR DESCRIPTION
**Pull request by mateuszkulpa**
# Related
Closes #128  

# Scope of work
- Set proper font and letter spacing for datepicker label (body-2-comfortable)

### CODE REVIEW

File: src/components/organisms/UiDatepicker/UiDatepicker.vue [hunk 1]
```diff
@@ -614,6 +614,8 @@ provide<ComputedRef<Record<string, DatepickerDatePart>>>('inputsIds', inputsIds)
 
   &__label {
     display: block;
+    font: functions.var($element + '-label', font, var(--font-body-2-comfortable));
+    letter-spacing: functions.var($element + '-label', letter-spacing, var(--letter-spacing-2-comfortable));
```
Comment (pspaczek) [inline src/components/organisms/UiDatepicker/UiDatepicker.vue:618]:
```suggestion
    font: functions.var($element + '-label', font, var(--font-body-2-comfortable));
    letter-spacing: functions.var($element + '-label', letter-spacing, var(--letter-spacing-2-comfortable));
```
You can use `ui-text--body-2-comfortable` modifier for UiText element

Comment (pspaczek) [reply src/components/organisms/UiDatepicker/UiDatepicker.vue:618]:
```
<UiText
  v-bind="getTextAttrs(datePart)"
  class="ui-text--body-2-comfortable ui-datepicker__label"
>
```

**Review by pspaczek — CHANGES_REQUESTED** [review]
:thank_you: @mateuszkulpa but in this case you should use UiText modifier :)

**Review by pspaczek — APPROVED** [review]
LGTM! :thank_you: @mateuszkulpa 🎖️
