### PR TITLE
fix: redundant label tag in UiMultipleChoicesItem option UiListItem

### LINKED ISSUE #381: [FIX] Remove attribute `label` from tag `label` to fix way of reading by Screen Readers
## Describe the bug
Tag `label` should have attribute `label` and Screen Reader read this label 3 times.

## To Reproduce
1. Turn on Screen Reader
2. In storybook open UiMultiSelectChoices
3. You heart label 3x

## Expected behavior
Tag `label` doesn't have attribute `label` ([documentation](https://www.w3schools.com/tags/ref_attributes.asp))
You can hear `label` only once

## Screenshots
image

### PR DESCRIPTION
**Pull request by pspaczek**
## Description
Filter redundant `label` from `option` object 

## Related Issue
Closes #381

## Screenshots (if appropriate):
Zrzut ekranu 2024-02-29 o 12 50 53

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: src/components/organisms/UiMultipleChoices/_internal/UiMultipleChoicesItem.vue [hunk 1]
```diff
@@ -296,6 +296,11 @@ const optionsToRender = computed(() => props.options.map((option) => ({
   },
 })));
 
+const listItemOptionAttrs = ({
+  // eslint-disable-next-line @typescript-eslint/no-unused-vars
```
Comment (AlanLes) [inline src/components/organisms/UiMultipleChoices/_internal/UiMultipleChoicesItem.vue:300]: Instead of disabling the eslint in cases like this, would you add the `ignoreRestSiblings` option to the `no-unused-vars` rule? 
Here's the link to the docs :) 
https://eslint.org/docs/latest/rules/no-unused-vars#ignorerestsiblings

You can do it with this line in the config.
`'@typescript-eslint/no-unused-vars': ['error', { ignoreRestSiblings: true }],`

Comment (pspaczek) [reply src/components/organisms/UiMultipleChoices/_internal/UiMultipleChoicesItem.vue]: Solved :thank_you:

**Review by sonya0504 — APPROVED** [review]
lgtm 🚀

**Review by AlanLes — COMMENTED** [review]
LGTM 👍 🪨 but there are some problems with `vue-tsc`
image

**Comment by pspaczek** [comment]
@AlanLes ts-check passed. If this PR is still LGTY please add approval.

**Review by AlanLes — APPROVED** [review]
LGTM :) Thanks! 😊
