### PR TITLE
fix: ts errors

### LINKED ISSUE #12: [BUG] ts errors
Resolve and fix typescript errors

### PR DESCRIPTION
**Pull request by ArkadiuszKrzymienski**
# Related issue

Close #12 

## Scope of work

- resolve ts errors
- remove unnecessary types
- add a script `check:types` which checks types in `.ts` and `.vue` files and displays errors as below

Zrzut ekranu 2022-09-28 o 10 33 23

### CODE REVIEW

File: src/components/organisms/UiDatepicker/_internal/UiDatepickerYearInput.vue [hunk 1]
```diff
@@ -61,9 +61,9 @@ const year = computed({
 });
 const validationError = computed(() => (year.value.length === 4 && !props.valid));
 const hasError = computed(() => (validationError.value || unfulfilledYearError.value || props.error));
-async function checkYear(event: InputEvent): Promise<void> {
+async function checkYear(event: Event) {
   unfulfilledYearError.value = false;
-  const inputValue = event.data;
+  const inputValue = (event as InputEvent).data;
```
Comment (AlanLes) [inline src/components/organisms/UiDatepicker/_internal/UiDatepickerYearInput.vue:66]: Q: Why these changes? Wasn't it cleaner with `InputEvent` in the function parameter and without this casting? And why did you remove the function's value returned type? 😅

File: src/utilities/helpers/focus-element/index.ts [hunk 2]
```diff
@@ -1,12 +1,15 @@
 /* eslint-disable import/prefer-default-export */
-export const focusElement = (el, focusVisible = false) => {
+/* eslint-disable consistent-return */
```
Comment (AlanLes) [inline src/utilities/helpers/focus-element/index.ts:2]: Q: Why is this necessary? I mean, is it really necessary to return this Promise? If so, then maybe it'd be reasonable to return some promise in every case? And then this comment `/* eslint-disable consistent-return */` wouldn't be necessary :) ESlint rules may be useful ;)

File: src/components/molecules/UiDropdown/UiDropdown.vue [hunk 3]
```diff
@@ -212,8 +212,8 @@ const {
   prevDropdownItem,
   selectedDropdownItem,
 } = useDropdownItems(dropdown);
-function disableArrows(event) {
-  if (['ArrowUp', 'ArrowDown'].indexOf(event.code) > -1) {
+function disableArrows(event: Event) {
+  if (['ArrowUp', 'ArrowDown'].indexOf((event as KeyboardEvent).code) > -1) {
```
[the remark this answers is not in the document]
Comment (ArkadiuszKrzymienski) [reply src/components/molecules/UiDropdown/UiDropdown.vue:216]: yes you are right, it is unnecessary, thanks 🙂

File: src/components/molecules/UiDropdown/UiDropdown.vue [hunk 4]
```diff
@@ -320,7 +320,7 @@ defineExpose({
   closeHandler,
 });
 
-const itemsToRender = computed<DropdownItemAsObj[]>(() => (props.items.map((item: DropdownItem, key) => {
+const itemsToRender = computed(() => (props.items.map((item: DropdownItem, key) => {
```
[the remark this answers is not in the document]
Comment (ArkadiuszKrzymienski) [reply src/components/molecules/UiDropdown/UiDropdown.vue:323]: 1. yes, there is no need to wrap returned value with `()`
2. It is unnecessary. You are right, typescript know it by inference
thanks 🙂

File: src/components/molecules/UiNavigation/UiNavigation.vue [hunk 5]
```diff
@@ -76,14 +71,10 @@ const nav = ref<HTMLElement | null>(null);
...
 provide('modifiers', modifiers);
-const itemsToRender = computed<NavigationRenderItem[]>(() => (props.items.map((item: NavigationItem, key: number) => {
-  const { name, text } = item;
-  return {
-    name: name || `navigation-item-${key}`,
-    text,
-    ...item,
-  };
-})));
+const itemsToRender = computed(() => (props.items.map((item: NavigationItem, key: number) => ({
```
[the remark this answers is not in the document]
Comment (ArkadiuszKrzymienski) [reply src/components/molecules/UiNavigation/UiNavigation.vue:74]: Yes, typescript know it by inference thanks 🙂

File: src/components/molecules/UiStepper/UiStepper.vue [hunk 6]
```diff
@@ -164,8 +162,8 @@ const currentStepDisplayText = computed(() => `
       ${currentStepDisplayNumber.value}/${props.steps.length} ${props.currentStep}
     `);
 const stepsProgress = computed(() => (currentStepDisplayNumber.value / stepsLength.value) * 100);
-const determineStep = (itemIndex: number, step: Step): DetermineStep => ({
-  tag: itemIndex >= indexOfActiveStep.value ? 'span' : undefined,
+const determineStep = (itemIndex: number, step: Step) => ({
+  tag: itemIndex >= indexOfActiveStep.value ? 'span' as HTMLTag : undefined,
```
[the remark this answers is not in the document]
Comment (ArkadiuszKrzymienski) [reply src/components/molecules/UiStepper/UiStepper.vue:166]: ok i will change it back 👍

File: src/components/organisms/UiDatepicker/_internal/UiDatepickerYearInput.vue (hunk 1 above)
Comment (ArkadiuszKrzymienski) [reply src/components/organisms/UiDatepicker/_internal/UiDatepickerYearInput.vue:66]: 1. If we have `InputEvent` in the function parameter then we have an error in the template because the input payload has type `Event`
2. I removed it, because the typescript knows it by inference

File: src/utilities/helpers/focus-element/index.ts (hunk 2 above)
Comment (ArkadiuszKrzymienski) [reply src/utilities/helpers/focus-element/index.ts:2]: A promise is necessary. I will add a promise to be consistent in all cases and will remove the ESlint comment as you wrote 🙂

File: src/components/atoms/UiCheckbox/UiCheckbox.vue [hunk 7]
```diff
@@ -70,8 +70,8 @@ import UiText from '../UiText/UiText.vue';
 import useInput from '../../../composable/useInput';
 import { keyboardFocus as vKeyboardFocus } from '../../../utilities/directives';
 
-export type CheckboxValue = string | object;
-export type CheckboxModelValue = boolean | object;
+export type CheckboxValue = string | Record<string, unknown>[];
```
Comment (AlanLes) [inline src/components/atoms/UiCheckbox/UiCheckbox.vue:73]: Q: Why is there an `unknown`? ;) Maybe it'd be nice to make usage of generic types here? 🤔 :) 
Something like this:
`type CheckboxValue<T> = string | Record<string, T>[];` 
WDYT? 🙂

**Review by AlanLes — COMMENTED** [review]
Nice job man! 🚀  You rock! 🎸 🎵 🎶

File: src/components/organisms/UiAccordion/_internal/UiAccordionItem.vue [hunk 8]
```diff
@@ -105,8 +106,8 @@ const props = defineProps({
 });
 const defaultProps = computed(() => ({
   settings: {
-    iconOpen: 'chevron-up',
-    iconClose: 'chevron-down',
+    iconOpen: 'chevron-up' as IconAsString,
```
Comment (pspaczek) [inline src/components/organisms/UiAccordion/_internal/UiAccordionItem.vue:109]: Q: Icon can by [Object, String] here we support just IconAsString. Should we change this type?

File: src/components/organisms/UiDatepicker/_internal/UiDatepickerDayTab.vue [hunk 9]
```diff
@@ -7,7 +7,7 @@
       :key="i"
       class="ui-datepicker-day-tab__item"
       :class="{
-        'ui-button--is-selected': day == i,
```
Comment (pspaczek) [inline src/components/organisms/UiDatepicker/_internal/UiDatepickerDayTab.vue:10]: 🙈

**Review by pspaczek — APPROVED** [review]
LGTM! Awesome. Please give answer for my questions :thank_you:
