### PR TITLE
fix: missing error class in UiPhoneNumber component

### LINKED ISSUE #382: [FIX] UiPhoneNumber input doesn't have error class
## Describe the bug
UiPhoneNumber input doesn't have error class

## Screenshots
Current:
image

Design:
image

### PR DESCRIPTION
**Pull request by pspaczek**
## Description
Support for `ui-phone-number--has-error`

## Related Issue
Closes #382

## Screenshots (if appropriate):
Zrzut ekranu 2024-02-29 o 12 41 17
Zrzut ekranu 2024-02-29 o 12 41 29

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: src/components/molecules/UiPhoneNumber/UiPhoneNumber.vue [hunk 1]
```diff
@@ -105,6 +103,13 @@ const modelValue = computed({
   get: () => props.modelValue,
   set: (value) => emit('update:modelValue', value),
 });
+const attrs = useAttrs() as { class:string };
+const hasError = computed(() => {
+  if (!attrs.class) {
+    return false;
+  }
+  return !!attrs.class.match(/ui-phone-number--has-error/gm);
+});
```
Comment (AlanLes) [inline src/components/molecules/UiPhoneNumber/UiPhoneNumber.vue:112]: It can be simplified
```suggestion
const hasError = computed(() => (!attrs.class) 
? false : !!attrs.class.match(/ui-phone-number--has-error/gm));
```

File: src/components/molecules/UiPhoneNumber/UiPhoneNumber.vue [hunk 2]
```diff
@@ -105,6 +103,13 @@ const modelValue = computed({
   get: () => props.modelValue,
   set: (value) => emit('update:modelValue', value),
 });
+const attrs = useAttrs() as { class:string };
```
Comment (AlanLes) [inline src/components/molecules/UiPhoneNumber/UiPhoneNumber.vue:106]: Why do you do `as { class:string };` here?

Comment (pspaczek) [reply src/components/molecules/UiPhoneNumber/UiPhoneNumber.vue]: Because of ts return `error` for class in `attrs`. You can see it now.

**Comment by sonya0504** [comment]
There are bugs in `UiPhoneNumber.stories.ts`
image

**Comment by sonya0504** [comment]
And also is `UiPhoneNumber.vue`
image

**Comment by pspaczek** [comment]
> And also is `UiPhoneNumber.vue` image

:thank_you: @sonya0504, I'm aware of that. Following @AlanLes's comment, I decided to retract my "solution" to demonstrate to him why I had implemented it in the first place.

**Comment by AlanLes** [comment]
> Check Types / vue-tsc (pull_request) Failing after 30s

File: src/components/molecules/UiPhoneNumber/UiPhoneNumber.vue [hunk 3]
```diff
@@ -35,18 +35,22 @@
...
+import type { DefineAttrsProps } from '../../../types';
 import type {
   PhoneCodeType,
   SupportedCountryCodeType,
 } from './helpers';
 
 export type CountryCodes = (PhoneCodeType & Record<string, unknown>)[];
 
-export interface UiPhoneNumberProps {
+export interface PhoneNumberProps {
```
Comment (pspaczek) [inline src/components/molecules/UiPhoneNumber/UiPhoneNumber.vue:53]: Related to https://component.infermedica.com/?path=/docs/contributing-guide-typescript-guidelines--docs#attrs-props

> Naming
Use the component name as a prefix, followed by the word AttrsProps as a suffix for the type of the component's inherited attributes. For example, MultipleAnswerAttrsProps for the UiMultipleAnswer component.

File: src/components/molecules/UiPhoneNumber/UiPhoneNumber.stories.ts [hunk 4]
```diff
@@ -138,7 +139,10 @@ export const WithError: StoryObj<typeof UiPhoneNumber> = {
     </UiFormField>`,
     };
   },
-  args: { error: 'Please enter the phone number' },
+  args: {
+    error: 'Please enter the phone number',
```
Comment (sonya0504) [inline src/components/molecules/UiPhoneNumber/UiPhoneNumber.stories.ts:143]: Still, one error left:
image

File: src/components/molecules/UiPhoneNumber/UiPhoneNumber.vue [hunk 5]
```diff
@@ -105,6 +106,10 @@ const modelValue = computed({
   get: () => props.modelValue,
   set: (value) => emit('update:modelValue', value),
 });
+const attrs:PhoneNumberAttrsProps = useAttrs();
+const hasError = computed(() => ((!attrs.class)
+  ? false
+  : attrs.class.includes('ui-phone-number--has-error')));
```
Comment (AlanLes) [inline src/components/molecules/UiPhoneNumber/UiPhoneNumber.vue:112]: I've heard that it's a good practice _to avoid negations_ in conditions whenever it's possible, whenever it makes sense, or whenever it doesn't obfuscate the meaning of code. 
Wouldn't it be easier to read with the opposite condition? Or is there a reason for the _negation_ in the first condition?
WDYT:
```suggestion
const hasError = computed(() => ((attrs.class)
  ? attrs.class.includes('ui-phone-number--has-error')
  : false));
```

I've also met the airbnb javascript styleguide, which includes many good patterns. One of them is _comparison shortcuts_, which suggest to **_Use shortcuts for booleans, but explicit comparisons for strings and numbers_** I think it could be extended to **Use shortcuts for booleans, but explicit comparisons for other types**. Would you agree?
According to that, maybe it'd be better to change `(attrs.class) ?` to an explicit comparison. :) WDYT?

**Review by AlanLes — COMMENTED** [review]
Only 1 thing that I think may be a good starting point for a discussion :)

File: src/components/molecules/UiPhoneNumber/UiPhoneNumber.vue (hunk 5 above)
Comment (pspaczek) [reply src/components/molecules/UiPhoneNumber/UiPhoneNumber.vue]: @AlanLes may I utilize 'explicit comparison' to check if the object has the key 'class'? As far as I know, I can use 'class' in attrs or attrs.hasOwnProperty('class'). This approach aligns with the guideline "Use shortcuts for booleans".

**Comment by pspaczek** [comment]
> Only 1 thing that I think may be a good starting point for a discussion :)

Your suggestions have been incorporated. Please review this pull request again.

**Review by AlanLes — APPROVED** [review]
LGTM! 👍 😁

**Review by sonya0504 — APPROVED** [review]
