### PR TITLE
fix: resolve ts errors

### LINKED ISSUE #99: [FIX] resolve ts errors

### PR DESCRIPTION
**Pull request by ArkadiuszKrzymienski**
# Related issue
Close #99 

# Scope of work
- resolved TS errors in `UiScale`, `UiRating`, and `UiMultipleAnswerItem`
- fixed translation in `UiRating`
- removed unnecessary imports

### CODE REVIEW

File: src/components/molecules/UiRating/UiRating.vue [hunk 1]
```diff
@@ -93,7 +93,7 @@
             <span
               v-bind="textLabelAttrs"
               class="visual-hidden"
-            >{{ defaultProps.translation.stars }}</span>
+            >{{ defaultProps.translation.stars(index) }}</span>
```
Comment (pspaczek) [inline src/components/molecules/UiRating/UiRating.vue:96]: @ArkadiuszKrzymienski chceck template in storybook for 1 star you have 0, for 2 you have 1 :)

Comment (ArkadiuszKrzymienski) [reply src/components/molecules/UiRating/UiRating.vue]: Thanks 🙂 I've already fixed it ✌️

**Review by pspaczek — APPROVED** [review]
LGTM! :thank_you: @ArkadiuszKrzymienski
