### PR TITLE
fix: translations for UiRating component

### LINKED ISSUE #220: [BUG] translation prop doesn't work for UiRating
Even if you pass `translation` prop to UiRating, a default (English) function is still used.

Reproduction:
https://stackblitz.com/edit/vitejs-vite-3t1xef?file=src%2FApp.vue

Current result:
UiRating doesn't respect `translation` prop
Screenshot 2023-06-13 at 13 29 47

Expected result:
UiRating respects `translation` prop

### PR DESCRIPTION
**Pull request by mateuszkulpa**
### Related issue
Closes #220 

### Scope of work
- Use translation from passed props instead of constant computed property

### CODE REVIEW

File: src/components/molecules/UiRating/UiRating.vue [hunk 1]
```diff
@@ -189,7 +189,6 @@ const defaultProps = computed(() => {
   const iconDefault: IconAttrsProps['icon'] = 'star-outlined';
   const iconActive: IconAttrsProps['icon'] = 'star-filled';
   return {
-    translation: { stars: (index: number) => (`${index} stars`) },
```
Comment (pspaczek) [inline src/components/molecules/UiRating/UiRating.vue:192]: this is the solution for your issue, please use it to keep consistency in our library 
```
translation: {
  stars: (index: number) => (`${index} stars`),
  ...props.translation,
},
```

**Review by pspaczek — APPROVED** [review]
:thank_you: @mateuszkulpa
