### PR TITLE
fix: incorrect position of underline element in UiTabs

### LINKED ISSUE #202: [BUG] Incorrect underline position in UiTabs placed in UiSidePanel
The issue appears only when the initial position of tabs is chaning, for example when side panel with tabs is opening.

Reproduction:
https://stackblitz.com/edit/vitejs-vite-axf5az?file=src%2FApp.vue

Current result:
The underline is positioned incorrectly.
Screenshot 2023-05-31 at 11 46 54

Expected result:
The underline is positioned correctly.
Screenshot 2023-05-31 at 11 47 00

### PR DESCRIPTION
**Pull request by KamilBartczak03**
### Related issue
Closes #202 

### Scope of work
- **Added better RWD support** When resizing tabs component underline was not updated.
- **Added vertical tabs support**. When we had more then one row of tabs underline was not displayed correctly.
- **Fixed issue with incorrect underline position** Underline pseudo element was not displayed in the right place when the fist tab was not selected by default.

### video

https://github.com/infermedica/component-library/assets/89569524/9a324a51-3330-4ae4-8739-4a6737d3b447

@pspaczek

### CODE REVIEW

File: src/components/organisms/UiTabs/UiTabs.vue [hunk 1]
```diff
@@ -75,32 +77,61 @@ const itemsToRender = computed<TabsProps['items']>(() => (props.items.map((item,
...
+const tabs = ref<OrNull<HTMLDivElement>>(null);
+const activeTabEl = ref<OrNull<HTMLElement>>(null);
+
+const containerX = ref(0);
+const containerY = ref(0);
+const containerH = ref(0);
+
 const offsetX = computed(() => {
-  if (activeTabHTMLElement.value === null) return 0;
+  const hack = containerX.value * 0;
```
Comment (KamilBartczak03) [inline src/components/organisms/UiTabs/UiTabs.vue:89]: I defined this hacky variable to make computed properties react to changes from resizeObserver.

Comment (mateuszkulpa) [reply src/components/organisms/UiTabs/UiTabs.vue:89]: @KamilBartczak03 I'd consider creating `watch` with multiple sources that modify `ref` value instead of this hack.
Watchers require more code, but it will be more obvious in terms of extending and debugging.

**Review by mateuszkulpa — CHANGES_REQUESTED** [review]
@KamilBartczak03 There are some issues with positioning when direction is `rtl`

Screenshot 2023-06-01 at 15 00 12

**Comment by KamilBartczak03** [comment]
@kubajmarek apparently It is because of the animation of the underline 🙈

**Comment by kubajmarek** [comment]
> @kubajmarek apparently It is because of the underline animation 🙈

Makes sense, although I wouldn't say that the tradeoff is worth it. Probably not worth it after it's already fixed, but personally I'd simplify it at the cost of animation, @pspaczek wdyt?

File: src/components/organisms/UiTabs/UiTabs.vue [hunk 2]
```diff
@@ -75,32 +80,61 @@ const itemsToRender = computed<TabsProps['items']>(() => (props.items.map((item,
...
+  if (activeTabEl.value === null) return 1;
   const firstTabRect = tabs.value?.children[0].children[0].getBoundingClientRect();
   if (!firstTabRect) return 1;
-  const activeTabRect = activeTabHTMLElement.value.getBoundingClientRect();
+  const activeTabRect = activeTabEl.value.getBoundingClientRect();
   return activeTabRect.width / firstTabRect.width;
 });
+
+const containerObserver = new ResizeObserver(([ { target } ]) => {
+  const rect = target.getBoundingClientRect();
```
Comment (pspaczek) [inline src/components/organisms/UiTabs/UiTabs.vue:116]: nothing important but :D why you wouldn't use restructuring? 
```
const { width, height, y } = target.getBoundingClientRect();
containerRect.w = width;
containerRect.h = height;
containerRect.y = y;
```
;)

**Comment by pspaczek** [comment]
@KamilBartczak03 nice. TBH multiline elements shouldn't be supported. You have a gray line only on the bottom elements. When you tab elements on the first line the highlighted line will be on the air (not on the line).

@kubajmarek IMO we should keep this animation. I love it and IMO we should be a modern application with micro-actions. 

@mateuszkulpa RTL works fine on chrome for me

**Comment by KamilBartczak03** [comment]
@pspaczek RTL works because I already fixed it :D

File: src/components/organisms/UiTabs/UiTabs.vue (hunk 2 above)
Comment (KamilBartczak03) [reply src/components/organisms/UiTabs/UiTabs.vue:116]: I did it on purpose because the linter forces me to split width, height and y into multiple lines

Comment (pspaczek) [reply src/components/organisms/UiTabs/UiTabs.vue:116]: yes, fine. We keen object and arrays one element per line. IMO is useful for CR when you add/remove/change something. In our approach, you can find these changes faster with everything in one line. You should find wich element are changed XD in line

**Review by pspaczek — APPROVED** [review]
:thank_you: LGTM @KamilBartczak03 thank you for your contribution
