### PR TITLE
fix: inactive Steps violate a11y Contrast rules

### LINKED ISSUE #222: [BUG] Inactive UiStepper steps violate a11y contrast rules
[UiStepper](https://main--639728541e2039caadfe5404.chromatic.com/iframe.html?args=&id=molecules-stepper--with-current-step&viewMode=story) now uses UiText instead of UiButtons for non-navigable steps, with `--color-text-disabled`. Unfortunately, on our background (`--color-background-subtle`), the contrast between the two is too low:

Screenshot 2023-06-14 at 10 57 56

Previously this wasn't an issue as those steps were disabled buttons, which don't have to obey the contrast rules.

### PR DESCRIPTION
**Pull request by kubajmarek**
Closes #222 

I decided to revert the change and have all steps become UiButtons. Not only it fixes the issue, but I think inactive buttons are overall more descriptive than switching between text and button element.

### CODE REVIEW

File: src/components/molecules/UiStepper/_internal/UiStepperStep.vue [hunk 1]
```diff
@@ -14,7 +14,7 @@
     >
       <component
         v-bind="itemAttrs"
-        :is="itemTag"
+        :is="UiButton"
```
Comment (pspaczek) [inline src/components/molecules/UiStepper/_internal/UiStepperStep.vue:17]: Why we can't use `UiButton` directly? I mean, we don't need `<component />` when we use static `UiButton`

File: src/components/molecules/UiStepper/_internal/UiStepperStep.vue [hunk 2]
```diff
@@ -81,27 +82,25 @@ const listItemAttrs = computed(() => ({
...
-const itemTag = computed(() => (isVisitedStep.value
-  ? UiButton
-  : UiText));
-const itemClass = computed(() => (isVisitedStep.value
-  ? [
+const itemClass = computed(() => (
+  [
     'ui-button--text',
     'ui-button--theme-secondary',
+    isInactiveStep.value ? 'ui-button--is-disabled' : '',
```
Comment (pspaczek) [inline src/components/molecules/UiStepper/_internal/UiStepperStep.vue:89]:
```suggestion
    isInactiveStep.value && 'ui-button--is-disabled',
```
shorter IMO

File: src/components/molecules/UiStepper/_internal/UiStepperStep.vue [hunk 3]
```diff
@@ -153,6 +152,17 @@ const itemAttrs = computed<ButtonAttrsProps | TextAttrsProps>(() => (isVisitedSt
     }
   }
 
+  &--is-current {
+    --button-color: var(--color-text-body);
+    --button-hover-color: var(--color-text-body);
+    --button-active-color: var(--color-text-body);
+    --button-font: var(--font-body-1-thick);
```
Comment (pspaczek) [inline src/components/molecules/UiStepper/_internal/UiStepperStep.vue:159]:
```suggestion
    --button-font: var(--font-body-1-thick);
    --button-letter-spacing: var(--letter-spacing-body-1-thick)
```
;)

**Review by pspaczek — CHANGES_REQUESTED** [review]

File: src/components/molecules/UiStepper/_internal/UiStepperStep.vue (hunk 3 above)
Comment (kubajmarek) [reply src/components/molecules/UiStepper/_internal/UiStepperStep.vue:159]: Shouldn't letter spacing be part of font variable? Feels inseparable.

File: src/components/molecules/UiStepper/_internal/UiStepperStep.vue (hunk 2 above)
Comment (kubajmarek) [reply src/components/molecules/UiStepper/_internal/UiStepperStep.vue:88]: Shorter but less readable.
@mateuszkulpa wdyt?

Comment (mateuszkulpa) [reply src/components/molecules/UiStepper/_internal/UiStepperStep.vue:88]: @kubajmarek I prefer the ternary syntax :D 
Also, I don't see any occurrence of `condition && class` in this repo, so it would be inconsistent.

**Review by pspaczek — APPROVED** [review]
:thank_you: @kubajmarek
